apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: psmdb-operator
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
  source:
    chart: psmdb-operator
    path: charts/psmdb-operator/
    repoURL: https://percona.github.io/percona-helm-charts/
    targetRevision: 1.15.4
    helm:
      releaseName: psmdb-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
